# Generated by Django 5.2.16 on 2026-07-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(blank=True, help_text='Local RTSP URL for the edge AI agent (optional until agent is connected).', max_length=500),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
