# Generated by Django 5.2.16 on 2026-07-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_camera_rtsp_and_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='LAN IP of the PC or IP camera (e.g. 192.168.1.45).', null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_port',
            field=models.PositiveIntegerField(blank=True, default=554, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(blank=True, help_text='Local RTSP/HTTP stream URL for the edge AI agent (optional).', max_length=500),
        ),
    ]
